In [1]:
import pandas as pd
import csv
import glob

In [2]:
path = ('../Resources1')        

all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0, error_bad_lines=False, quoting=csv.QUOTE_NONE)
    li.append(df)

frame = pd.concat(li, axis=0, ignore_index=True)

In [3]:
frame.head()

,"""tripduration""","""starttime""","""stoptime""","""start station id""","""start station name""","""start station latitude""","""start station longitude""","""end station id""","""end station name""","""end station latitude""","""end station longitude""","""bikeid""","""usertype""","""birth year""","""gender"""
0,320,"""2019-01-01 00:01:47.4010""","""2019-01-01 00:07:07.5810""",3160.0,"""Central Park West & W 76 St""",40.778968,-73.973747,3283.0,"""W 89 St & Columbus Ave""",40.788221,-73.970416,15839,"""Subscriber""",1971,1
1,316,"""2019-01-01 00:04:43.7360""","""2019-01-01 00:10:00.6080""",519.0,"""Pershing Square North""",40.751873,-73.977706,518.0,"""E 39 St & 2 Ave""",40.747804,-73.973442,32723,"""Subscriber""",1964,1
2,591,"""2019-01-01 00:06:03.9970""","""2019-01-01 00:15:55.4380""",3171.0,"""Amsterdam Ave & W 82 St""",40.785247,-73.976673,3154.0,"""E 77 St & 3 Ave""",40.773142,-73.958562,27451,"""Subscriber""",1987,1
3,2719,"""2019-01-01 00:07:03.5450""","""2019-01-01 00:52:22.6500""",504.0,"""1 Ave & E 16 St""",40.732219,-73.981656,3709.0,"""W 15 St & 6 Ave""",40.738046,-73.996430,21579,"""Subscriber""",1990,1
4,303,"""2019-01-01 00:07:35.9450""","""2019-01-01 00:12:39.5020""",229.0,"""Great Jones St""",40.727434,-73.993790,503.0,"""E 20 St & Park Ave""",40.738274,-73.987520,35379,"""Subscriber""",1979,1

In [4]:
frame = frame[(frame['"birth year"'] > 1920) & (frame['"birth year"'] <= 1965)]

In [5]:
frame

,"""tripduration""","""starttime""","""stoptime""","""start station id""","""start station name""","""start station latitude""","""start station longitude""","""end station id""","""end station name""","""end station latitude""","""end station longitude""","""bikeid""","""usertype""","""birth year""","""gender"""
1,316,"""2019-01-01 00:04:43.7360""","""2019-01-01 00:10:00.6080""",519.0,"""Pershing Square North""",40.751873,-73.977706,518.0,"""E 39 St & 2 Ave""",40.747804,-73.973442,32723,"""Subscriber""",1964,1
17,3494,"""2019-01-01 00:18:57.5640""","""2019-01-01 01:17:11.5700""",3171.0,"""Amsterdam Ave & W 82 St""",40.785247,-73.976673,3164.0,"""Columbus Ave & W 72 St""",40.777057,-73.978985,35785,"""Subscriber""",1954,1
52,524,"""2019-01-01 00:32:14.4270""","""2019-01-01 00:40:59.2060""",3467.0,"""W Broadway & Spring Street""",40.724947,-74.001659,127.0,"""Barrow St & Hudson St""",40.731724,-74.006744,34778,"""Subscriber""",1963,2
57,837,"""2019-01-01 00:35:04.5250""","""2019-01-01 00:49:01.6370""",458.0,"""11 Ave & W 27 St""",40.751396,-74.005226,334.0,"""W 20 St & 7 Ave""",40.742388,-73.997262,29066,"""Subscriber""",1960,1
62,604,"""2019-01-01 00:38:16.1910""","""2019-01-01 00:48:20.9080""",435.0,"""W 21 St & 6 Ave""",40.741740,-73.994156,380.0,"""W 4 St & 7 Ave S""",40.734011,-74.002939,30275,"""Subscriber""",1955,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35662720,436,"""2020-10-13 14:37:58.9460""","""2020-10-13 14:45:15.3660""",3681.0,"""Grand St""",40.715178,-74.037683,3199.0,"""Newport Pkwy""",40.728745,-74.032108,44492,"""Subscriber""",1960,1
35662724,1113,"""2020-10-13 14:42:22.3730""","""2020-10-13 15:00:56.3430""",3272.0,"""Jersey & 3rd""",40.723332,-74.045953,3280.0,"""Astor Place""",40.719282,-74.071262,45343,"""Subscriber""",1960,1
35662728,952,"""2020-10-13 14:45:43.2080""","""2020-10-13 15:01:35.5850""",3677.0,"""Glenwood Ave""",40.727551,-74.071061,3205.0,"""JC Medical Center""",40.716540,-74.049638,42545,"""Subscriber""",1959,1
35662734,274,"""2020-10-13 14:53:39.1720""","""2020-10-13 14:58:13.7350""",3639.0,"""Harborside""",40.719252,-74.034234,3202.0,"""Newport PATH""",40.727224,-74.033759,45274,"""Subscriber""",1960,1
35662741,270,"""2020-10-13 15:05:35.0860""","""2020-10-13 15:10:05.3430""",3207.0,"""Oakland Ave""",40.737604,-74.052478,3640.0,"""Journal Square""",40.733670,-74.062500,44744,"""Subscriber""",1963,2

In [6]:
frame.count()

"tripduration"               4121741
"starttime"                  4121741
"stoptime"                   4121741
"start station id"           4121741
"start station name"         4121741
"start station latitude"     4121741
"start station longitude"    4121741
"end station id"             4121741
"end station name"           4121741
"end station latitude"       4121741
"end station longitude"      4121741
"bikeid"                     4121741
"usertype"                   4121741
"birth year"                 4121741
"gender"                     4121741
dtype: int64

In [7]:
frame['"start station id"'].value_counts()

519.0     36835
435.0     31050
497.0     29576
3255.0    28055
490.0     22684
          ...
4084.0        1
4031.0        1
4152.0        1
4132.0        1
3954.0        1
Name: "start station id", Length: 1200, dtype: int64

In [8]:
Over_55_df = frame.rename(columns={'"tripduration"':"Trip Duration", '"starttime"':"Start Time", 
                                      '"stoptime"':"Stop Time", '"start station id"':"Start Station ID",
                                      '"start station name"':"Start Station Name", '"start station latitude"':"Start Station Latitude", 
                                      '"start station longitude"':"Start Station Longitude", '"end station id"':"End Station ID",
                                      '"end station name"':"End Station Name", '"end station latitude"':"End Station Latitude", 
                                      '"end station longitude"':"End Station Longitude", '"bikeid"':"Bike ID", '"usertype"':"User Type", 
                                      '"birth year"':"Birth Year", '"gender"':"Gender"})
Over_55_df.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
1,316,"""2019-01-01 00:04:43.7360""","""2019-01-01 00:10:00.6080""",519.0,"""Pershing Square North""",40.751873,-73.977706,518.0,"""E 39 St & 2 Ave""",40.747804,-73.973442,32723,"""Subscriber""",1964,1
17,3494,"""2019-01-01 00:18:57.5640""","""2019-01-01 01:17:11.5700""",3171.0,"""Amsterdam Ave & W 82 St""",40.785247,-73.976673,3164.0,"""Columbus Ave & W 72 St""",40.777057,-73.978985,35785,"""Subscriber""",1954,1
52,524,"""2019-01-01 00:32:14.4270""","""2019-01-01 00:40:59.2060""",3467.0,"""W Broadway & Spring Street""",40.724947,-74.001659,127.0,"""Barrow St & Hudson St""",40.731724,-74.006744,34778,"""Subscriber""",1963,2
57,837,"""2019-01-01 00:35:04.5250""","""2019-01-01 00:49:01.6370""",458.0,"""11 Ave & W 27 St""",40.751396,-74.005226,334.0,"""W 20 St & 7 Ave""",40.742388,-73.997262,29066,"""Subscriber""",1960,1
62,604,"""2019-01-01 00:38:16.1910""","""2019-01-01 00:48:20.9080""",435.0,"""W 21 St & 6 Ave""",40.741740,-73.994156,380.0,"""W 4 St & 7 Ave S""",40.734011,-74.002939,30275,"""Subscriber""",1955,1

In [9]:
Over_55_df.dtypes

Trip Duration                int64
Start Time                  object
Stop Time                   object
Start Station ID           float64
Start Station Name          object
Start Station Latitude     float64
Start Station Longitude    float64
End Station ID             float64
End Station Name            object
End Station Latitude       float64
End Station Longitude      float64
Bike ID                      int64
User Type                   object
Birth Year                   int64
Gender                       int64
dtype: object

In [10]:
Over_55_df["Gender"] = Over_55_df['Gender'].astype(str)

In [11]:
Over_55_df['Gender'] = Over_55_df['Gender'].replace({'1.0': 'Male', '2.0':'Female'})
Over_55_df['Gender'].value_counts()

1    3053532
2    1047523
0      20686
Name: Gender, dtype: int64

In [12]:
Over_55_df.reset_index(level=None, drop=True, inplace=False, col_level=0, col_fill='')

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,316,"""2019-01-01 00:04:43.7360""","""2019-01-01 00:10:00.6080""",519.0,"""Pershing Square North""",40.751873,-73.977706,518.0,"""E 39 St & 2 Ave""",40.747804,-73.973442,32723,"""Subscriber""",1964,1
1,3494,"""2019-01-01 00:18:57.5640""","""2019-01-01 01:17:11.5700""",3171.0,"""Amsterdam Ave & W 82 St""",40.785247,-73.976673,3164.0,"""Columbus Ave & W 72 St""",40.777057,-73.978985,35785,"""Subscriber""",1954,1
2,524,"""2019-01-01 00:32:14.4270""","""2019-01-01 00:40:59.2060""",3467.0,"""W Broadway & Spring Street""",40.724947,-74.001659,127.0,"""Barrow St & Hudson St""",40.731724,-74.006744,34778,"""Subscriber""",1963,2
3,837,"""2019-01-01 00:35:04.5250""","""2019-01-01 00:49:01.6370""",458.0,"""11 Ave & W 27 St""",40.751396,-74.005226,334.0,"""W 20 St & 7 Ave""",40.742388,-73.997262,29066,"""Subscriber""",1960,1
4,604,"""2019-01-01 00:38:16.1910""","""2019-01-01 00:48:20.9080""",435.0,"""W 21 St & 6 Ave""",40.741740,-73.994156,380.0,"""W 4 St & 7 Ave S""",40.734011,-74.002939,30275,"""Subscriber""",1955,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4121736,436,"""2020-10-13 14:37:58.9460""","""2020-10-13 14:45:15.3660""",3681.0,"""Grand St""",40.715178,-74.037683,3199.0,"""Newport Pkwy""",40.728745,-74.032108,44492,"""Subscriber""",1960,1
4121737,1113,"""2020-10-13 14:42:22.3730""","""2020-10-13 15:00:56.3430""",3272.0,"""Jersey & 3rd""",40.723332,-74.045953,3280.0,"""Astor Place""",40.719282,-74.071262,45343,"""Subscriber""",1960,1
4121738,952,"""2020-10-13 14:45:43.2080""","""2020-10-13 15:01:35.5850""",3677.0,"""Glenwood Ave""",40.727551,-74.071061,3205.0,"""JC Medical Center""",40.716540,-74.049638,42545,"""Subscriber""",1959,1
4121739,274,"""2020-10-13 14:53:39.1720""","""2020-10-13 14:58:13.7350""",3639.0,"""Harborside""",40.719252,-74.034234,3202.0,"""Newport PATH""",40.727224,-74.033759,45274,"""Subscriber""",1960,1
4121740,270,"""2020-10-13 15:05:35.0860""","""2020-10-13 15:10:05.3430""",3207.0,"""Oakland Ave""",40.737604,-74.052478,3640.0,"""Journal Square""",40.733670,-74.062500,44744,"""Subscriber""",1963,2